ARCH            = $(shell uname -m | sed s,i[3456789]86,ia32,)
CFLAGS          = -I/usr/include/efi -I/usr/include/efi/$(ARCH) -fpic -ffreestanding -fno-stack-protector -fno-stack-check -fshort-wchar -mno-red-zone
LDFLAGS         = -nostdlib -znocombreloc -T /usr/lib/elf_$(ARCH)_efi.lds -shared -Bsymbolic -L /usr/lib /usr/lib/crt0-efi-$(ARCH).o

SOURCES = $(wildcard src/boot/*.c)
OBJECTS = $(SOURCES:.c=.o)
TARGET = BOOTX64.EFI

all: $(TARGET)

$(TARGET): $(OBJECTS)
	ld $(LDFLAGS) $^ -o $@ -lefi -lgnuefi

%.o: %.c
	gcc $(CFLAGS) -c $< -o $@

clean:
	rm -f src/boot/*.o $(TARGET)
